In [1]:
import ML_Framework

In [2]:
test_model = ML_Framework.Model(user_defined_model='lr')

In [3]:
test_model.transform()

In [5]:
# This code may not be run on GFG IDE
# as required packages are not found.
	
# STRATIFIES K-FOLD CROSS VALIDATION { 10-fold }

# Import Required Modules.
from statistics import mean, stdev
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold

# create StratifiedKFold object
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
lst_accu_stratified = []

# store all splits
X_train = []
X_test = []
y_train = []
y_test = []

for train_index, test_index in skf.split(test_model.X_scaled, test_model.y):
	# split X and y
	x_train_fold, x_test_fold = test_model.X_scaled[train_index], test_model.X_scaled[test_index]
	y_train_fold, y_test_fold = test_model.y[train_index], test_model.y[test_index]
	
	# store splits
	X_train.append(x_train_fold)
	X_test.append(x_test_fold)
	y_train.append(y_train_fold)
	y_test.append(y_test_fold)
	
	# 
	test_model.user_defined_model.fit(x_train_fold, y_train_fold)
	lst_accu_stratified.append(test_model.user_defined_model.score(x_test_fold, y_test_fold))

# Print the output.
print('List of possible accuracy:', lst_accu_stratified)
print('\nMaximum Accuracy That can be obtained from this model is:',
	max(lst_accu_stratified)*100, '%')
print('\nMinimum Accuracy:',
	min(lst_accu_stratified)*100, '%')
print('\nOverall Accuracy:',
	mean(lst_accu_stratified)*100, '%')
print('\nStandard Deviation is:', stdev(lst_accu_stratified))

c:\Users\czime\OneDrive\Privát\Egyetem\PostGrad\NBA-ML-project\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\czime\OneDrive\Privát\Egyetem\PostGrad\NBA-ML-project\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
   

List of possible accuracy: [0.991812673980678, 0.990501146413364, 0.9924664264657713, 0.9918113331149688, 0.9929577464788732, 0.9918113331149688, 0.9918113331149688, 0.9919751064526695, 0.9924664264657713, 0.9906649197510645]

Maximum Accuracy That can be obtained from this model is: 99.29577464788733 %

Minimum Accuracy: 99.05011464133639 %

Overall Accuracy: 99.18278445353099 %

Standard Deviation is: 0.0007621248239491918


c:\Users\czime\OneDrive\Privát\Egyetem\PostGrad\NBA-ML-project\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
x_test_fold

array([[0.6       , 0.12653061, 0.10131894, ..., 0.        , 0.        ,
        0.        ],
       [0.25      , 0.06632653, 0.06726619, ..., 0.        , 1.        ,
        0.        ],
       [0.7       , 0.45204082, 0.10623501, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.375     , 0.13163265, 0.15527578, ..., 0.        , 0.        ,
        0.        ],
       [0.075     , 0.01020408, 0.067506  , ..., 0.        , 0.        ,
        0.        ],
       [0.225     , 0.06020408, 0.05659472, ..., 0.        , 0.        ,
        0.        ]])

In [6]:
y_pred, cm, cp = test_model.evaluate(test_model.pred)

In [6]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [7]:
cp

0           1  accuracy     macro avg  weighted avg
precision      0.990817    0.015873  0.980758      0.503345      0.981796
recall         0.989752    0.017699  0.980758      0.503726      0.980758
f1-score       0.990284    0.016736  0.980758      0.503510      0.981276
support    12100.000000  113.000000  0.980758  12213.000000  12213.000000

In [4]:
cm

array([[12104,     0],
       [    0,   109]], dtype=int64)

In [7]:
test_model.X_test

GP  Min_per   Ortg   usg   eFG  TS_per  ORB_per  DRB_per  AST_per  \
14241   8      1.1   52.4  20.1  16.7   21.58      0.0      7.3      0.0   
58274  22     56.9  135.1  12.6  79.4   75.99      6.6     15.5      4.5   
60387  16      6.5   70.6  18.8  37.5   37.14      3.9      1.9      3.2   
20957  22     53.3   93.8  17.6  46.6   46.84      1.4      7.8     17.4   
9339   29     56.8  115.7  18.9  60.8   65.98      3.1     10.9     18.9   
...    ..      ...    ...   ...   ...     ...      ...      ...      ...   
57207   5      2.1   90.7  43.1  36.4   36.36     48.3     13.8     12.8   
14750  11      6.0   91.7  31.5  41.7   42.82      4.9     15.3     16.8   
16914   1      0.2    0.0  29.5   0.0    0.00      0.0      0.0      0.0   
9136   27     24.7   94.9  20.3  54.7   55.45     11.2     16.9      7.2   
44738  33     70.2  111.8  23.1  54.6   58.45      1.7     10.6     15.3   

       TO_per  ...    treb     ast     stl     blk      pts  drafted_flag  \
14241     0.0  ...  0.1250  0.0000  0.0000  0.0000   0.3750             0   
58274    13.0  ...  4.8182  0.4545  0.5455  2.3182   7.9545             0   
60387    21.0  ...  0.2778  0.1667  0.1667  0.0000   1.2222             0   
20957    14.5  ...  2.0000  2.0000  0.5455  0.2273   6.6818             0   
9339     18.5  ...  2.5517  1.6897  0.7241  0.0345   8.1724             0   
...       ...  ...     ...     ...     ...     ...      ...           ...   
57207    15.3  ...  2.5714  0.4286  0.0000  0.1429   3.0000             0   
14750     7.8  ...  1.1818  0.4545  0.1818  0.1818   3.4545             0   
16914   100.0  ...  0.0000  0.0000  0.0000  0.0000   0.0000             0   
9136     24.5  ...  2.4074  0.2963  0.2222  0.3333   3.3704             0   
44738    16.3  ...  3.2571  1.9714  1.3714  0.1143  13.6286             0   

       yr_Fr  yr_Jr  yr_None  yr_So  
14241      0      0        0      0  
58274      0      0        0      1  
60387      1      0        0      0  
20957      0      0        0      1  
9339       0      0        0      0  
...      ...    ...      ...    ...  
57207      0      0        0      1  
14750      0      1        0      0  
16914      1      0        0      0  
9136       1      0        0      0  
44738      0      0        0      1  

[12213 rows x 60 columns]

In [11]:
col_list = test_model.df.columns.tolist()
col_list.pop(-6) # 'drafted_flag'
col_list.append('drafted_flag')
col_list[-10:]

['ast',
 'stl',
 'blk',
 'pts',
 'yr_Fr',
 'yr_Jr',
 'yr_None',
 'yr_So',
 'yr_Sr',
 'drafted_flag']

In [ ]:
# first 
test_df = np.hstack([np.array(logreg_model.X_test),np.array(lr_y_pred).reshape(12213,1)])
np.set_printoptions(formatter={'float_kind':"{:.1f}".format})